language: node_js
node_js:
  - "8.12.0"
before_install:
  - "npm i -g npm@6.4.1"
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
    - script:
        - "npm run lint"
        - "truffle compile"
        - "npm run test"
      stage: "lint & tests"
